[env:test_dfplayer]
platform = espressif32
board = esp32dev
framework = arduino

; Cấu hình Serial Monitor
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Cấu hình upload
upload_speed = 921600

; Thư viện cho test DFPlayer
lib_deps = 
    dfrobot/DFRobotDFPlayerMini@^1.0.6

; Cấu hình build cho test
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    
; Chỉ định file main cho test
build_src_filter = 
    +<test_dfplayer.cpp>
    -<main.cpp>
    -<animations.cpp>

; Cấu hình partition
board_build.partitions = huge_app.csv